# Custom loss function for VZS-VC
import torch
import torch.nn as nn
from torch import Tensor


# Loss function for the generator in VZS-VC, combining reconstruction loss, adversarial loss, and feature matching loss
class GeneratorLoss(nn.Module):
    def __init__(self, lambda_recon: float = 45.0, lambda_adv: float = 1.0, lambda_fm: float = 2.0):
        """
        Initialize the GeneratorLoss module

        Args:
            lambda_recon (float, optional): Weight for the reconstruction loss component. Defaults to 45.0.
            lambda_adv (float, optional): Weight for the adversarial loss component. Defaults to 1.0.
            lambda_fm (float, optional): Weight for the feature matching loss component. Defaults to 2.0.
        """
        super().__init__()
        self.lambda_recon = lambda_recon
        self.lambda_adv = lambda_adv
        self.lambda_fm = lambda_fm

        # Define the loss functions for each component
        self.l1_loss = nn.L1Loss(reduction="none")
        self.mse_loss = nn.MSELoss(reduction="none")

    def forward(
        self, target: Tensor, output: Tensor, dis_gen: Tensor,
        fmap_gen: list[Tensor], fmap_target: list[Tensor], mask_indices: Tensor
    ) -> Tensor:
        """
        Compute the total generator loss as a weighted sum of reconstruction loss, adversarial loss, and feature matching loss.

        Args:
            target (Tensor): The ground truth Mel-spectrogram features of shape (N, 2T, n_mel_bins).
            output (Tensor): The generated Mel-spectrogram features of shape (N, 2T, n_mel_bins).
            dis_gen (Tensor): The discriminator's validity scores for the generated samples of shape (N, T).

            fmap_gen (list[Tensor]): The discriminator's intermediate feature maps for the generated samples. List of tensors of shape (N, D, T).
            fmap_target (list[Tensor]): The discriminator's intermediate feature maps for the real samples. List of tensors of shape (N, D, T).
            mask_indices (Tensor): A boolean tensor of shape (N, T) indicating time steps generated by the generator (True) or not (False).

        Returns:
            Tensor: The computed total generator loss.
        """
        # Reconstruction Loss: L1 loss averaged only over the generated time steps (where mask_indices is True)
        recon_loss: Tensor = self.l1_loss(output, target) * mask_indices.repeat_interleave(repeats=2, dim=-1).unsqueeze(-1) # (N, 2T, n_mel_bins) -> (N, 2T, 1) -> (N, 2T, n_mel_bins)
        recon_loss = recon_loss.sum() / (2 * mask_indices.sum() * target.shape[-1] + 1e-8) # Average only over generated time steps

        # Adversarial Loss: MSE loss against target label 1 for the discriminator's output on generated samples
        adv_loss: Tensor = self.mse_loss(dis_gen, torch.ones_like(dis_gen)) * mask_indices # (N, T)
        adv_loss = adv_loss.sum() / (mask_indices.sum() + 1e-8) # Average only over generated time steps

        # Feature Matching Loss: L1 loss between discriminator feature maps for generated and real samples, averaged over generated time steps
        fm_loss: Tensor = sum((self.l1_loss(fmap_g, fmap_t.detach()) * mask_indices.unsqueeze(1)).mean(dim=1)
                              for fmap_g, fmap_t in zip(fmap_gen, fmap_target)) # (N, T)
        fm_loss = fm_loss.sum() / (mask_indices.sum() + 1e-8) # Average only over generated time steps

        # Total Generator Loss
        total_loss: Tensor = self.lambda_recon * recon_loss + self.lambda_adv * adv_loss + self.lambda_fm * fm_loss

        return total_loss
    

# Loss function for the discriminator in VZS-VC
class DiscriminatorLoss(nn.Module):
    def __init__(self):
        """
        Initialize the DiscriminatorLoss module
        """
        super().__init__()
        self.mse_loss = nn.MSELoss(reduction="none")

    def forward(
        self,
        dis_gen: Tensor, dis_target: Tensor,
        mask_indices: Tensor, token_length: Tensor
    ) -> Tensor:
        """
        Compute the discriminator loss as the sum of real and fake losses.

        Args:
            dis_gen (Tensor): The discriminator's validity scores for generated samples of shape (N, T).
            dis_target (Tensor): The discriminator's validity scores for target samples of shape (N, T).
            mask_indices (Tensor): A boolean tensor of shape (N, T) indicating time steps generated by the generator (True) or not (False).
            token_length (Tensor): A tensor of shape (N,) indicating the actual length of each sequence in the batch.

        Returns:
            Tensor: The computed total discriminator loss.
        """
        # Create a padding mask to ignore padded time steps in the loss calculation
        N, T = mask_indices.shape
        nonpad_mask = torch.arange(T, device=mask_indices.device).unsqueeze(0) < token_length.unsqueeze(1) # (N, T)

        # Real Loss: MSE loss against target label 1 for real samples
        real_loss: Tensor = self.mse_loss(dis_target, torch.ones_like(dis_target)) # (N, T)

        # Fake Loss: MSE loss against masked target for generated samples
        fake_loss: Tensor = self.mse_loss(dis_gen, (~mask_indices).float()) # (N, T)

        # Combine real and fake losses, applying the padding mask to ignore padded time steps
        total_loss: Tensor = (real_loss + fake_loss) * nonpad_mask # (N, T)
        total_loss = total_loss.sum() / (nonpad_mask.sum() + 1e-8) # Average only over valid time steps

        return total_loss