# Configuration files (YAML) for model architecture
# Configuration for the ERes2Net-V2 model used as the timbre encoder module
eres2net-v2_module:
  checkpoint_path: 'checkpoints/timbre_encoder.safetensors'
  n_mel_bins: 80
  sampling_rate: 16000

# Configuration for the FCPE model used as the pitch encoder module
fcpe_module:
  sampling_rate: 16000
  hop_size: 320
  f0_min: 32.7
  f0_max: 1975.5

# Configuration for the Zipformer2 model used as the content encoder module
zipformer2_module:
  checkpoint_path: 'checkpoints/content_encoder.safetensors'
  dither: 0
  high_freq: -400
  n_mel_bins: 80
  sampling_rate: 16000
  snip_edges: False

# Configuration for the LocalRMS method used as the amplitude encoder module
local_rms_module:
  window_size: 960
  hop_size: 320

# Configuration for the NeuCodec model used as the codec module
neucodec_module:
  pretrained_model_name_or_path: 'neuphonic/neucodec'